backend:
  name: git-gateway
  branch: master
media_folder: statics
collections:
  - label: Posts
    name: posts
    description: List of posts
    folder: posts
    extension: md
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Content
        name: body
        widget: markdown
site_url: 'http://localhost:3000/'
local_backend: true
